- packages/workbox/index.js
Use case: https://documentation.onesignal.com/docs/web-push-sdk-setup-https#section-can-onesignal-integrate-with-another-service-worker-on-my-site-or-a-progressive-web-app-
> Add option to register third-party SW

- README.md
- remove few space (Editor settings) 
- add an parenthesis in the exemple: 
`console.log('Received NotificationOpened:', data )}`
Thanks ;)
> add parenthesis in a console.log

- packages/manifest/index.js
for CDN use it is important that the manifest is serverd frome the same domain, and not from the CDN.
Even though it is actually allowed to server the manifest from a different domain, you will run into other troubles like start_url is cross-origin and so on that this approach is the easiest one to fix it. (see issue #18)
after this PR it's possible to overwrite the publicPath for manifest module (like it is already possible in workbox module). my nuxt.config.js looks therefore like this (I overwrite the publicPath explicity by my _nuxt path without the cdn)
```
modules: [
['@nuxtjs/pwa', {workbox: {publicPath: '/_nuxt/'}, manifest: {publicPath: "/_nuxt/"}}],
],
```
regards
Simon
> allow overidding of publicPath for manifest module

- packages/meta/index.js
Uses the [`vmid` option](https://github.com/declandewet/vue-meta#lists-of-tags) of vue-meta
> Add unique identifiers to meta fields

- packages/meta/index.js
Fixes a (self-introduced :sweat_smile:) bug which emits og:url if `ogUrl` is set to true, but no `ogHost` is defined.
This will also fix the build.
> Only set og:url when it has been defined through ogHost or options

- packages/meta/index.js
We shouldn't replace empty `head.title` with `options.name` when the `head.titleTemplate` is a function.
The `head.titleTemplate` function is used to generate the default title when `head.title` is intentionally set to be null. See [this](https://github.com/declandewet/vue-meta#titletemplate-string--function)
> Improve the behavior of empty-title replacement

- packages/manifest/index.js
In the case of Basic Authentication, manifest.json isn't downloaded properly.
To solve this problem, I added the `crossorigin` attribute for `link` tag.
We can set the attribute as below.
```javascript:nuxt.config.js
modules: [
['@nuxtjs/pwa', {manifest: {crossorigin: "use-credentials"}}],
],
```
As a result, `link` tag is generated as below.
```html:index.html
<link data-n-head="true" rel="manifest" href="/_nuxt/manifest.json" crossorigin="use-credentials"/>
```
regards
Hiroki
> feat: add new attribute to link tag for manifest.json

- packages/workbox/index.js
By default, runtimeCache is added for base URL as below.
```js
workbox.routing.registerRoute(new RegExp('/.*'), workbox.strategies.networkFirst({}), 'GET')
```
Then, I have an problem.
When I add runtimeCache for `/api/xxxxxx` and set the strategy except for `networkFirst`, for example `cacheFirst`, it doesn't work because of the order.
I want to change the default runtimeCache order to avoid this problem.
```js
workbox: {
skipWaiting: true,
clientsClaim: true,
runtimeCaching: [
{
urlPattern: '/api/xxxxxx/.*',
handler: 'cacheFirst',
method: 'GET',
strategyOptions: {
cacheExpiration: {
maxAgeSeconds: 60 * 15, // 15min
},
cacheableResponse: {
statuses: [200],
},
},
},\
],
},
```
```js
workbox.routing.registerRoute(new RegExp('/.*'), workbox.strategies.networkFirst({}), 'GET') …
```
> feat: change the order of default runtimeCache

- README.md
- docs/README.md
This PR adds missing spaces in `README.md` and `docs/README.md`.
> docs: fix typos in readme files

- packages/workbox/index.js
Related: [#97](https://github.com/nuxt-community/pwa-module/issues/97)
maybe it is caused routing order when register this route (/.*). i try to place it last
> [FIX] routing order for runtime caching (/.*)

- packages/workbox/lib/defaults.js
Hey @pi0, great work on rewriting the workbox module!
I just noticed that `workboxExtensions` is missing in `defaults.js`, that's actually breaking the build as the `readJSFiles` function expects an Array.
> fix: add workboxExtensions to defaults

- packages/pwa-utils/index.js
adding a route to `workbox.runtimeCaching` results in
```
✖ Nuxt Fatal Error                                 
│                                                      
│   TypeError: Cannot read property '0' of undefined 
```
if its handler is undefined
> fix(pwa-utils): handle non-strings in `startCase`

- docs/modules/workbox.md
- packages/workbox/templates/sw.js
- test/__snapshots__/pwa.test.js.snap
- test/fixture/nuxt.config.js
This is a proposal to add the ability to configure the workbox cache names.
See https://developers.google.com/web/tools/workbox/guides/configure-workbox#configure_cache_names for more information on this.
> Allow cache names to be configured

- packages/icon/index.js
Handle situation where iconSrc could be `null`, `undefined` or falsey.
> fix(icon): handle situation where the iconSrc is `null` or `undefined`

- CHANGELOG.md
- docs/modules/workbox.md
- lib/manifest/module.js
- lib/module.js
- package.json
As mentioned in #247 , this PR adds a tip in the examples section on how to use `nuxt.config` options to prevent the automatic PWA mini-infobar (Add to Home Screen Banner) on mobil devices.
> docs: tip for `pwa.manifest.display: 'browser'`

- docs/modules/icon.md
I hope that typo fix will save some debugging time 😅
> docs: fix typo in `icon.md`

- docs/modules/workbox.md
The 'workbox.strategies.cacheFirst()' function has been deprecated and will be removed in a future version of Workbox.
Please use 'new workbox.strategies.CacheFirst()' instead.
> docs: use CacheFirst instead of  cacheFirst

- package.json
- yarn.lock
defu@0.0.3 does not work on IE11 because it uses arrow function.
This PR change will update to defu@0.0.4.
> chore(deps): update dependency defu to v0.0.4

- docs/modules/icon.md
The description of sizes is placed in the wrong position.
> docs: fix wrong position of a description

- docs/modules/workbox.md
- lib/workbox/defaults.js
The project I am working on has two code bases in the same domain (hurriyetemlak.com mobile & desktop). Sometimes there may be a conflict due to the operation of sw in some cases. It fixed when I changed sw's name. I saw how to change it isn't in the document.
> docs: added new option to change to name of the sw

- docs/setup.md
I am using the version `2.12.2` of nuxt and the module does not generate the files when registered in the `modules` section of `nuxt.config.js`. So I guess now it is required to be in the `buildModules`. 
I also changed it to a dev dependency as the [buildModules documentation](https://nuxtjs.org/guide/modules#build-only-modules) suggests.
> docs(setup): change 'modules' to 'buildModules'

- lib/icon/module.js
.len is undefined, should be .length.
> fix(module): icon purpose warning appearing when it shouldn't

- lib/meta/module.js
I stumbled upon this console warning today but the URL was wrong and it pointed to a 404 page of the doc. This should be the right URL to use.
> fix(icon): update warning url to docs

- lib/workbox/templates/sw.js
According to [the Workbox Migration Guide](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v4#removal_of_makerequest_from_workbox-strategies):
> In v5, `handle()` treats `request` as a required parameter, and will not fall back to using `event.request`. Make sure that you pass in a valid request when calling `handle()`.<sup>1</sup>
However, our [`sw.js` template](https://github.com/nuxt-community/pwa-module/blob/1e1ae7bf11bd4e36c566d9514308c83409691a10/lib/workbox/templates/sw.js#L66) only passes `event` parameter. 
This causes websites with `offlinePage` setup always redirects to the offline page.
This pull request fixes it.
<sub><sup>1. However, [the reference docs](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-strateg …
> fix(workbox): missing required parameter request for handle()

- lib/icon/module.js
When we start the server e.g. with --inspect and forking it
with the default process.execArgv it will cause an error,
because it wants to start the inspector again on the same port.
This patch fixes this issue.
Related to https://github.com/nuxt-community/pwa-module/issues/218
> fix(icon): fork without original process args

- docs/content/en/meta.md
I added the meta property and helpful article for `appleStatusBarStyle`. I realized that in the [docs](https://pwa.nuxtjs.org/meta#applestatusbarstyle), there's no explanation on what values we should put here. 
The values for meta `apple-mobile-web-app-status-bar-style` are
- `default`
- `black`
- `black-translucent`
Perhaps these values and a one-line explanation could also be added to the Nuxt PWA docs? 
The article linked is [Changing The iOS Status Bar Of Your Progressive Web App](https://medium.com/appscope/changing-the-ios-status-bar-of-your-progressive-web-app-9fc8fbe8e6ab) by Appscope.
> docs: add meta and article for appleStatusBarStyle

- docs/content/en/manifest.md
- docs/content/en/meta.md
- lib/manifest/module.js
- lib/meta/module.js
Fixes issue #223 
Removes the defaults for the meta `theme-color` and the manifest `theme-color` taken from the nuxt loading bar.
To keep user configuration to a minimum, the manifest theme-color's default is now the meta one, if set.
In most real world scenarios they tend to coincide.
Docs updated to reflect the changes, plus a minor fix to the icon/meta links.
> fix(manifest): do not use nuxt loading bar color as default `theme_color`

- lib/meta/module.js
The favicon must be accessible from any page and it does not matter how deep the page is. The only possible solution is to use a relative url.
> fix(meta): add missing `router.base` prefix to favicon

- docs/content/en/meta.md
Added an inline summary of the values for appleStatusBarStyle (https://github.com/nuxt-community/pwa-module/pull/357#issuecomment-701997310).
I also added a link to Apple's official documentation (archive): https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW4
In the next commit, I made it clear that `mobileAppIOS` is required
> docs: explain `appleStatusBarStyle` values

- lib/icon/module.js
- lib/meta/module.js
When the icon is set to false in config, or when the icon is not found correctly, pwa._iosSplash is undefined.
This prevents access to its proprieties and thus the nuxt build failure.
I added also a console.warn that might help in debugging future issues, to try to make it obvious that no icons are actually being generated since the path to the base icon is wrong.
Fixes #355 and #334
> fix(meta): prevent build failure for ios splash image when no icon is used

- docs/content/en/setup.md
- lib/icon/module.js
- lib/manifest/module.js
- lib/meta/meta.json
- lib/meta/meta.merge.js
- lib/meta/module.js
- lib/meta/plugin.js
- lib/utils/index.js
- test/__snapshots__/pwa.test.js.snap
- test/fixture/nuxt.config.js
For a long time, we had to always add `@nuxtjs/pwa` for production to fill `options.meta` (providing icons, etc).
This refactor, exports `.nuxt/pwa/meta.json` file which is merged at runtime using a nuxt plugin with user provided `head`. Also SPA meta support (+ static `200.html` ) is preserved by loading same json file and using same merging strategy. 
Note: Users using `ssr: false` in production mode, have to still use `modules` instead of `buildModules`
Fixes #341
> feat(meta): merge head at runtime

- lib/icon/module.js
- lib/manifest/module.js
- lib/meta/module.js
- lib/meta/module.runtime.js
- lib/module.js
- lib/utils/index.js
- lib/workbox/module.js
- lib/workbox/options.js
- lib/workbox/utils.js
- package.json
- types/manifest.d.ts
Fix issues with nuxt build cache for `static` target.
Related issues: #367, #352, #353
This PR mainly fixes #353
When using `nuxt generate` and cache hit happens, we skip `nuxt build` step and directly generate. However as `build:*` hooks won't be called anymore (even tough `buildModules` are called!)
0. 491f440936e107c424864a1aa1121e6995d4e87b ensures `sw.js` is properly emitted (temporary fix)
1. Run pwa modules both if `_build` flag exists (`nuxt dev`, `nuxt build` and first optional stage of `nuxt generate`) or `target` is `static`. Downside is we call modules twice when cache miss occurs but seems only way
2. Directly emit files and generate template as even tough `buildModules` are called for generate's second stage builder is not loaded so webpack hook to emit assets and …
> fix: support build cache

- docs/content/en/setup.md
Just some `npm i` devDependencies syntax fix.
> docs: fixes dev npm syntax

- src/pwa.ts
Currently trying to configure only some options for modules results in type errors when using TypeScript. This PR aims to resolve that issue by marking them as optional in the declaration files.
> fix(types): mark module options fields as optional

- src/meta.ts
The favicon head links were pushed without `hid` and `name` and they weren't deduplicated in `mergeMeta`: https://github.com/nuxt-community/pwa-module/blob/245aadc3c3111c1eff0bf18ff775bb248a708867/lib/meta.utils.js#L13-L19
As a result they were appended every time the page was visited, causing a memory leak and crashing the server after some time.
> fix(meta): add missing `hid` to icon tags
