nuxt-community/pwa-module

docs/modules/workbox.md, packages/workbox/templates/sw.template.js
Related to https://github.com/nuxt-community/pwa-module/issues/35
=> feat: Add support of StrategyOptions to cache

docs/modules/meta.md
Looks like this got lost in doc updates.
=> Document new ogImage support

docs/readme.md
Just fixing a typo and correcting the writing of OneSignal
=> Update readme.md fixing some tiny typos

packages/meta/index.js
please let me know if i am mistaken, what exactly the syntax is
=> fix og:image option

packages/meta/index.js
This should fix circleci build regarding eslint.
=> fix eslint error

packages/workbox/index.js
=> feat(workbox): disable caching for sw.js by default

packages/workbox/index.js
replace hard coded 'static' path with ```this.options.dir.static``` if exists
=> fix static path hardcoded

docs/modules/meta.md
=> docs: fix twitter meta

docs/modules/icon.md
=> docs(icon): fix default sizes

docs/modules/workbox.md
Please check out https://pwa.nuxtjs.org/modules/workbox.html#workbox-window section
=> updated docs with typo in code example

docs/README.md
This commit adds a note to the docs specifying what version of the module they're for.
Fixes #206
=> Add version note

docs/modules/workbox.md
Resolves https://github.com/nuxt-community/pwa-module/issues/220
=> docs: only match same host for `rangeRequests` 

docs/modules/workbox.md
I think some brackets were missing :)
=> docs: fix wrong code reference

docs/modules/workbox.md
From https://github.com/nuxt-community/pwa-module/issues/239#issuecomment-597813613
=> docs: add an example for refresh to update implementation

docs/modules/workbox.md
https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.strategies    404 page
=> docs(workbox): update external link

docs/content/en/workbox.md
RangeRequestsPlugin: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v4#plugin_classes_renamed
CachingStrategy: https://github.com/nuxt-community/pwa-module/blob/master/types/workbox.d.ts
=> docs: update with new workbox casing convention

docs/content/en/manifest.md
fix broken link to icon module doc
=> docs: fix broken link

docs/content/en/workbox.md, lib/meta/module.js, lib/workbox/module.js, lib/workbox/options.js, lib/workbox/templates/sw.js, lib/workbox/utils.js, test/__snapshots__/pwa.test.js.snap, test/fixture/nuxt.config.js, types/workbox.d.ts
- Refactor with runtime logic for more readability
- Pass options as plain json object
- Update docs and types for new `strategyPlugins`
=> refactor(pwa): avoid templates as much as possible

docs/nuxt.config.js
Added missing pwa manifest name.
=> docs: add pwa manifest name

docs/content/en/icon.md
This is the current path using version `3.1.2`
=> docs: update cache directory path

docs/content/en/workbox.md
- replace broken url with the updated one
=> docs: update workbox link
